// --- START: breed lists ---
export const DOG_BREEDS = [
  'Aspin (Philippine Native)',
  'Mixed Breed',
  'Labrador Retriever',
  'Golden Retriever',
  'German Shepherd',
  'Shih Tzu',
  'Siberian Husky',
  'Pomeranian',
  'Poodle',
  'Beagle',
  'Chihuahua',
  'Dachshund',
  'Bulldog (English)',
  'French Bulldog',
  'Rottweiler',
  'Doberman Pinscher',
  'Belgian Malinois',
  'Border Collie',
  'Corgi (Pembroke Welsh)',
  'Yorkshire Terrier',
  'Maltese',
  'Jack Russell Terrier',
  'Japanese Spitz',
  'Chow Chow',
  'Great Dane',
  'American Pit Bull Terrier',
  'American Bully',
  'Shar Pei',
  'Shiba Inu',
  'Miniature Pinscher',
  'Whippet',
  'Other / Not Sure',
] as const;

export const CAT_BREEDS = [
  'Puspin (Domestic Shorthair)',
  'Mixed Breed',
  'Persian',
  'Siamese',
  'British Shorthair',
  'Scottish Fold',
  'Maine Coon',
  'Ragdoll',
  'Bengal',
  'Sphynx',
  'American Shorthair',
  'Russian Blue',
  'Norwegian Forest Cat',
  'Birman',
  'Burmese',
  'Exotic Shorthair',
  'Oriental Shorthair',
  'Turkish Angora',
  'Himalayan',
  'Domestic Longhair',
  'Ragamuffin',
  'Savannah',
  'Tonkinese',
  'Munchkin',
  'Other / Not Sure',
] as const;
// --- END: breed lists ---
